package main

import (
	"archive/zip"
	"bufio"
	"bytes"
	"context"
	"crypto/tls"
	"encoding/base64"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"log"
	"net"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/creack/pty"
	"github.com/gorilla/websocket"
	"github.com/shirou/gopsutil/v3/cpu"
	"github.com/shirou/gopsutil/v3/disk"
	"github.com/shirou/gopsutil/v3/host"
	"github.com/shirou/gopsutil/v3/load"
	"github.com/shirou/gopsutil/v3/mem"
	gnet "github.com/shirou/gopsutil/v3/net"
	"github.com/shirou/gopsutil/v3/process"
)

type agentConfig struct {
	BackendURL      string
	Token           string
	Name            string
	MetricsInterval time.Duration
	InsecureTLS     bool
}

type storedAgentConfig struct {
	BackendURL      string `json:"backend_url"`
	Token           string `json:"token"`
	Name            string `json:"name"`
	MetricsInterval string `json:"metrics_interval"`
	InsecureTLS     bool   `json:"insecure_tls"`
}

const (
	defaultBackendURL      = "ws://localhost:8380"
	defaultMetricsInterval = 2 * time.Second

	colorReset  = "\033[0m"
	colorRed    = "\033[31m"
	colorGreen  = "\033[32m"
	colorYellow = "\033[33m"
	colorBlue   = "\033[34m"
	colorCyan   = "\033[36m"
)

var colorLogsEnabled bool

type Agent struct {
	cfg agentConfig

	conn   *websocket.Conn
	sendMu sync.Mutex

	termMu    sync.RWMutex
	terminals map[string]*terminalSession

	netMu     sync.Mutex
	lastRX    uint64
	lastTX    uint64
	lastNetAt time.Time

	diskMu        sync.Mutex
	lastDiskRead  uint64
	lastDiskWrite uint64
	lastDiskAt    time.Time
}

type terminalSession struct {
	cmd     *exec.Cmd
	ptyFile *os.File
}

type commandMessage struct {
	Type      string          `json:"type"`
	Command   string          `json:"command"`
	RequestID string          `json:"request_id"`
	Payload   json.RawMessage `json:"payload"`
}

type deployPayload struct {
	DeployID    uint   `json:"deploy_id"`
	Source      string `json:"source"`
	RepoURL     string `json:"repo_url"`
	Branch      string `json:"branch"`
	ProjectType string `json:"project_type"`
	ZipData     string `json:"zip_data"`
}

func main() {
	initLogger()

	cliCfg := agentConfig{}
	flag.StringVar(&cliCfg.BackendURL, "backend", defaultBackendURL, "Backend WebSocket base URL")
	flag.StringVar(&cliCfg.Token, "token", "", "Agent token generated by backend")
	flag.StringVar(&cliCfg.Name, "name", "", "Optional server name shown in panel")
	flag.DurationVar(&cliCfg.MetricsInterval, "metrics-interval", defaultMetricsInterval, "Metrics push interval")
	flag.BoolVar(&cliCfg.InsecureTLS, "insecure-tls", false, "Skip TLS cert verification (dev only)")
	flag.Parse()
	setFlags := collectSetFlags()

	cfg, cfgPath, err := resolveAgentConfig(cliCfg, setFlags)
	if err != nil {
		logFatal("resolve agent config: %v", err)
	}

	normalizedURL, err := normalizeBackendURL(cfg.BackendURL)
	if err != nil {
		logFatal("invalid backend URL: %v", err)
	}
	cfg.BackendURL = normalizedURL

	if err := saveAgentConfig(cfgPath, cfg); err != nil {
		logWarn("failed to save config to %s: %v", cfgPath, err)
	} else {
		logSuccess("config saved to %s", cfgPath)
	}

	logInfo("agent started: backend=%s, name=%q, metrics_interval=%s", cfg.BackendURL, cfg.Name, cfg.MetricsInterval)

	agent := &Agent{
		cfg:       cfg,
		terminals: make(map[string]*terminalSession),
	}
	agent.runForever()
}

func initLogger() {
	log.SetOutput(os.Stdout)
	log.SetFlags(log.LstdFlags)
	colorLogsEnabled = isTerminal(os.Stdout) && strings.TrimSpace(os.Getenv("NO_COLOR")) == ""
}

func isTerminal(stream *os.File) bool {
	if stream == nil {
		return false
	}
	info, err := stream.Stat()
	if err != nil {
		return false
	}
	return info.Mode()&os.ModeCharDevice != 0
}

func colorize(color, text string) string {
	if !colorLogsEnabled {
		return text
	}
	return color + text + colorReset
}

func logInfo(format string, args ...any) {
	log.Printf("%s %s", colorize(colorBlue, "[INFO]"), fmt.Sprintf(format, args...))
}

func logWarn(format string, args ...any) {
	log.Printf("%s %s", colorize(colorYellow, "[WARN]"), fmt.Sprintf(format, args...))
}

func logError(format string, args ...any) {
	log.Printf("%s %s", colorize(colorRed, "[ERROR]"), fmt.Sprintf(format, args...))
}

func logSuccess(format string, args ...any) {
	log.Printf("%s %s", colorize(colorGreen, "[OK]"), fmt.Sprintf(format, args...))
}

func logFatal(format string, args ...any) {
	log.Fatalf("%s %s", colorize(colorRed, "[FATAL]"), fmt.Sprintf(format, args...))
}

func collectSetFlags() map[string]bool {
	setFlags := make(map[string]bool)
	flag.Visit(func(f *flag.Flag) {
		setFlags[f.Name] = true
	})
	return setFlags
}

func resolveAgentConfig(cliCfg agentConfig, setFlags map[string]bool) (agentConfig, string, error) {
	configPath, err := defaultConfigPath()
	if err != nil {
		return agentConfig{}, "", err
	}

	cfg := agentConfig{
		BackendURL:      defaultBackendURL,
		MetricsInterval: defaultMetricsInterval,
	}

	storedCfg, hasStoredConfig, err := loadAgentConfig(configPath)
	if err != nil {
		return agentConfig{}, "", err
	}
	if hasStoredConfig {
		cfg = mergeConfig(cfg, storedCfg)
		logInfo("loaded config from %s", configPath)
	}

	applyCLIOverrides(&cfg, cliCfg, setFlags)

	if cfg.MetricsInterval <= 0 {
		cfg.MetricsInterval = defaultMetricsInterval
	}

	interactive := isTerminal(os.Stdin)
	reader := bufio.NewReader(os.Stdin)

	if strings.TrimSpace(cfg.Token) == "" {
		if !interactive {
			return agentConfig{}, "", fmt.Errorf("agent token is empty; pass -token or run in interactive mode")
		}
		logInfo("interactive setup: token is required")
		token, err := promptRequired(reader, "Enter agent token: ")
		if err != nil {
			return agentConfig{}, "", err
		}
		cfg.Token = token
	}

	if strings.TrimSpace(cfg.Name) == "" {
		if interactive {
			name, err := promptInput(reader, "Enter server name (empty = system hostname): ")
			if err != nil {
				return agentConfig{}, "", err
			}
			cfg.Name = name
		}
		if strings.TrimSpace(cfg.Name) == "" {
			cfg.Name = fallbackSystemName()
			logInfo("server name is empty, using system hostname: %s", cfg.Name)
		}
	}

	return cfg, configPath, nil
}

func defaultConfigPath() (string, error) {
	configDir, err := os.UserConfigDir()
	if err != nil || strings.TrimSpace(configDir) == "" {
		home, homeErr := os.UserHomeDir()
		if homeErr != nil {
			if err != nil {
				return "", err
			}
			return "", homeErr
		}
		configDir = filepath.Join(home, ".config")
	}
	return filepath.Join(configDir, "novex", "agent.json"), nil
}

func loadAgentConfig(path string) (agentConfig, bool, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return agentConfig{}, false, nil
		}
		return agentConfig{}, false, err
	}

	var stored storedAgentConfig
	if err := json.Unmarshal(content, &stored); err != nil {
		return agentConfig{}, false, fmt.Errorf("decode config: %w", err)
	}

	cfg := agentConfig{
		BackendURL:  strings.TrimSpace(stored.BackendURL),
		Token:       strings.TrimSpace(stored.Token),
		Name:        strings.TrimSpace(stored.Name),
		InsecureTLS: stored.InsecureTLS,
	}
	if intervalText := strings.TrimSpace(stored.MetricsInterval); intervalText != "" {
		if duration, err := time.ParseDuration(intervalText); err == nil {
			cfg.MetricsInterval = duration
		}
	}

	return cfg, true, nil
}

func mergeConfig(base, extra agentConfig) agentConfig {
	if v := strings.TrimSpace(extra.BackendURL); v != "" {
		base.BackendURL = v
	}
	if v := strings.TrimSpace(extra.Token); v != "" {
		base.Token = v
	}
	if v := strings.TrimSpace(extra.Name); v != "" {
		base.Name = v
	}
	if extra.MetricsInterval > 0 {
		base.MetricsInterval = extra.MetricsInterval
	}
	base.InsecureTLS = extra.InsecureTLS
	return base
}

func applyCLIOverrides(cfg *agentConfig, cliCfg agentConfig, setFlags map[string]bool) {
	if setFlags["backend"] {
		cfg.BackendURL = strings.TrimSpace(cliCfg.BackendURL)
	}
	if setFlags["token"] {
		cfg.Token = strings.TrimSpace(cliCfg.Token)
	}
	if setFlags["name"] {
		cfg.Name = strings.TrimSpace(cliCfg.Name)
	}
	if setFlags["metrics-interval"] {
		cfg.MetricsInterval = cliCfg.MetricsInterval
	}
	if setFlags["insecure-tls"] {
		cfg.InsecureTLS = cliCfg.InsecureTLS
	}
}

func promptInput(reader *bufio.Reader, prompt string) (string, error) {
	fmt.Print(colorize(colorCyan, prompt))
	line, err := reader.ReadString('\n')
	if err != nil && !errors.Is(err, io.EOF) {
		return "", err
	}
	line = strings.TrimSpace(line)
	if errors.Is(err, io.EOF) && line == "" {
		return "", io.EOF
	}
	return line, nil
}

func promptRequired(reader *bufio.Reader, prompt string) (string, error) {
	for {
		value, err := promptInput(reader, prompt)
		if err != nil {
			return "", err
		}
		if value != "" {
			return value, nil
		}
		logWarn("value cannot be empty")
	}
}

func fallbackSystemName() string {
	hostName, err := os.Hostname()
	if err != nil {
		return "server"
	}
	hostName = strings.TrimSpace(hostName)
	if hostName == "" {
		return "server"
	}
	return hostName
}

func saveAgentConfig(path string, cfg agentConfig) error {
	stored := storedAgentConfig{
		BackendURL:      strings.TrimSpace(cfg.BackendURL),
		Token:           strings.TrimSpace(cfg.Token),
		Name:            strings.TrimSpace(cfg.Name),
		MetricsInterval: cfg.MetricsInterval.String(),
		InsecureTLS:     cfg.InsecureTLS,
	}

	content, err := json.MarshalIndent(stored, "", "  ")
	if err != nil {
		return err
	}
	content = append(content, '\n')

	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}

	tmpPath := path + ".tmp"
	if err := os.WriteFile(tmpPath, content, 0o600); err != nil {
		return err
	}
	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return err
	}
	return nil
}

func normalizeBackendURL(raw string) (string, error) {
	u, err := url.Parse(strings.TrimSpace(raw))
	if err != nil {
		return "", err
	}
	if u.Scheme == "http" {
		u.Scheme = "ws"
	}
	if u.Scheme == "https" {
		u.Scheme = "wss"
	}
	if u.Scheme != "ws" && u.Scheme != "wss" {
		return "", fmt.Errorf("scheme must be ws/wss/http/https")
	}
	u.Path = strings.TrimRight(u.Path, "/")
	if u.Host == "" {
		return "", fmt.Errorf("missing host")
	}
	return u.String(), nil
}

func (a *Agent) runForever() {
	backoff := 1 * time.Second
	for {
		err := a.connectAndRun()
		if err != nil {
			logWarn("agent disconnected: %v", err)
		}
		logInfo("reconnect in %s", backoff)
		time.Sleep(backoff)
		if backoff < 30*time.Second {
			backoff *= 2
			if backoff > 30*time.Second {
				backoff = 30 * time.Second
			}
		}
	}
}

func (a *Agent) connectAndRun() error {
	wsURL := strings.TrimRight(a.cfg.BackendURL, "/") + "/agent/ws?token=" + url.QueryEscape(a.cfg.Token)
	if name := strings.TrimSpace(a.cfg.Name); name != "" {
		wsURL += "&name=" + url.QueryEscape(name)
	}
	dialer := websocket.Dialer{HandshakeTimeout: 10 * time.Second}
	if a.cfg.InsecureTLS {
		dialer.TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
	}

	conn, _, err := dialer.Dial(wsURL, nil)
	if err != nil {
		return err
	}
	a.conn = conn
	defer func() {
		a.closeAllTerminals()
		_ = conn.Close()
		a.conn = nil
	}()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	go a.metricsLoop(ctx)
	logSuccess("connected to %s", wsURL)

	for {
		_, payload, err := conn.ReadMessage()
		if err != nil {
			return err
		}
		a.handleMessage(payload)
	}
}

func (a *Agent) handleMessage(payload []byte) {
	var envelope struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(payload, &envelope); err != nil {
		return
	}

	switch envelope.Type {
	case "command":
		var msg commandMessage
		if err := json.Unmarshal(payload, &msg); err != nil {
			return
		}
		go a.handleCommand(msg)
	case "terminal_input":
		var msg struct {
			SessionID string `json:"session_id"`
			Data      string `json:"data"`
		}
		if err := json.Unmarshal(payload, &msg); err != nil {
			return
		}
		_ = a.writeTerminalInput(msg.SessionID, msg.Data)
	case "terminal_resize":
		var msg struct {
			SessionID string `json:"session_id"`
			Rows      int    `json:"rows"`
			Cols      int    `json:"cols"`
		}
		if err := json.Unmarshal(payload, &msg); err != nil {
			return
		}
		_ = a.resizeTerminal(msg.SessionID, msg.Rows, msg.Cols)
	case "terminal_close":
		var msg struct {
			SessionID string `json:"session_id"`
		}
		if err := json.Unmarshal(payload, &msg); err != nil {
			return
		}
		a.closeTerminal(msg.SessionID)
	case "ping":
		_ = a.sendJSON(map[string]any{"type": "pong"})
	}
}

func (a *Agent) handleCommand(msg commandMessage) {
	respondError := func(err error) {
		a.sendCommandResponse(msg.RequestID, false, nil, err.Error())
	}

	switch msg.Command {
	case "ping":
		a.sendCommandResponse(msg.RequestID, true, map[string]any{"pong": true}, "")
	case "get_metrics":
		metrics, err := a.collectMetrics()
		if err != nil {
			respondError(err)
			return
		}
		a.sendCommandResponse(msg.RequestID, true, metrics, "")
	case "run_command":
		var payload struct {
			Command string `json:"command"`
		}
		if err := json.Unmarshal(msg.Payload, &payload); err != nil {
			respondError(fmt.Errorf("invalid payload"))
			return
		}
		stdout, stderr, exitCode, runErr := runShellCommand(payload.Command)
		resp := map[string]any{
			"stdout":    stdout,
			"stderr":    stderr,
			"exit_code": exitCode,
		}
		if runErr != nil && exitCode < 0 {
			respondError(runErr)
			return
		}
		a.sendCommandResponse(msg.RequestID, true, resp, "")
	case "get_processes":
		processes, err := a.collectProcesses(30)
		if err != nil {
			respondError(err)
			return
		}
		a.sendCommandResponse(msg.RequestID, true, map[string]any{"processes": processes}, "")
	case "kill_process":
		var payload struct {
			PID int `json:"pid"`
		}
		if err := json.Unmarshal(msg.Payload, &payload); err != nil {
			respondError(fmt.Errorf("invalid payload"))
			return
		}
		if payload.PID <= 0 {
			respondError(fmt.Errorf("invalid pid"))
			return
		}
		if err := killProcess(payload.PID); err != nil {
			respondError(err)
			return
		}
		a.sendCommandResponse(msg.RequestID, true, map[string]any{"success": true}, "")
	case "run_terminal":
		var payload struct {
			SessionID string `json:"session_id"`
			Rows      int    `json:"rows"`
			Cols      int    `json:"cols"`
		}
		if err := json.Unmarshal(msg.Payload, &payload); err != nil {
			respondError(fmt.Errorf("invalid payload"))
			return
		}
		if payload.SessionID == "" {
			respondError(fmt.Errorf("session_id is required"))
			return
		}
		if err := a.openTerminal(payload.SessionID, payload.Rows, payload.Cols); err != nil {
			respondError(err)
			return
		}
		a.sendCommandResponse(msg.RequestID, true, map[string]any{"session_id": payload.SessionID}, "")
	case "deploy":
		var payload deployPayload
		if err := json.Unmarshal(msg.Payload, &payload); err != nil {
			respondError(fmt.Errorf("invalid payload"))
			return
		}
		if payload.DeployID == 0 {
			respondError(fmt.Errorf("deploy_id is required"))
			return
		}
		go a.runDeploy(payload)
		a.sendCommandResponse(msg.RequestID, true, map[string]any{"accepted": true}, "")
	default:
		logError("unknown command received: %s", msg.Command)
		respondError(fmt.Errorf("unknown command: %s", msg.Command))
	}
}

func runShellCommand(command string) (stdout, stderr string, exitCode int, err error) {
	command = strings.TrimSpace(command)
	if command == "" {
		return "", "", -1, errors.New("command is empty")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, "bash", "-lc", command)
	var outBuf bytes.Buffer
	var errBuf bytes.Buffer
	cmd.Stdout = &outBuf
	cmd.Stderr = &errBuf

	err = cmd.Run()
	stdout = outBuf.String()
	stderr = errBuf.String()
	exitCode = 0

	if err != nil {
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) {
			exitCode = exitErr.ExitCode()
			return stdout, stderr, exitCode, nil
		}
		exitCode = -1
		return stdout, stderr, exitCode, err
	}

	return stdout, stderr, exitCode, nil
}

func (a *Agent) sendJSON(v any) error {
	a.sendMu.Lock()
	defer a.sendMu.Unlock()

	if a.conn == nil {
		return errors.New("connection is not established")
	}
	if err := a.conn.SetWriteDeadline(time.Now().Add(10 * time.Second)); err != nil {
		return err
	}
	return a.conn.WriteJSON(v)
}

func (a *Agent) sendCommandResponse(requestID string, success bool, data any, errText string) {
	message := map[string]any{
		"type":       "command_response",
		"request_id": requestID,
		"success":    success,
	}
	if data != nil {
		message["data"] = data
	}
	if errText != "" {
		message["error"] = errText
	}
	_ = a.sendJSON(message)
}

func (a *Agent) metricsLoop(ctx context.Context) {
	send := func() {
		metrics, err := a.collectMetrics()
		if err != nil {
			logWarn("collect metrics error: %v", err)
			return
		}
		if err := a.sendJSON(map[string]any{"type": "metrics", "data": metrics}); err != nil {
			logWarn("send metrics error: %v", err)
		}
	}

	send()
	ticker := time.NewTicker(a.cfg.MetricsInterval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			send()
		}
	}
}

func (a *Agent) collectMetrics() (map[string]any, error) {
	cpuUsage := 0.0
	cpuValues, err := cpu.Percent(0, false)
	if err == nil && len(cpuValues) > 0 {
		cpuUsage = cpuValues[0]
	}

	cores, _ := cpu.Counts(true)
	loadAvg, _ := load.Avg()
	vmem, _ := mem.VirtualMemory()
	diskUsage, _ := disk.Usage("/")
	diskCounters, _ := disk.IOCounters()
	uptime, _ := host.Uptime()
	netCounters, _ := gnet.IOCounters(false)

	topProcesses, _ := a.collectProcesses(5)
	temperature := readTemperature()

	rxBytes := uint64(0)
	txBytes := uint64(0)
	if len(netCounters) > 0 {
		rxBytes = netCounters[0].BytesRecv
		txBytes = netCounters[0].BytesSent
	}
	rxSpeed, txSpeed := a.calculateNetSpeed(rxBytes, txBytes)

	diskReadBytes := uint64(0)
	diskWriteBytes := uint64(0)
	for _, counter := range diskCounters {
		diskReadBytes += counter.ReadBytes
		diskWriteBytes += counter.WriteBytes
	}
	diskReadSpeed, diskWriteSpeed := a.calculateDiskSpeed(diskReadBytes, diskWriteBytes)

	result := map[string]any{
		"cpu": map[string]any{
			"usage":    cpuUsage,
			"cores":    cores,
			"load_avg": []float64{loadAvg.Load1, loadAvg.Load5, loadAvg.Load15},
		},
		"ram": map[string]any{
			"total":   vmem.Total,
			"used":    vmem.Used,
			"free":    vmem.Free,
			"percent": vmem.UsedPercent,
		},
		"disk": map[string]any{
			"total":       diskUsage.Total,
			"used":        diskUsage.Used,
			"free":        diskUsage.Free,
			"percent":     diskUsage.UsedPercent,
			"read_bytes":  diskReadBytes,
			"write_bytes": diskWriteBytes,
			"read_speed":  diskReadSpeed,
			"write_speed": diskWriteSpeed,
		},
		"network": map[string]any{
			"rx_bytes": rxBytes,
			"tx_bytes": txBytes,
			"rx_speed": rxSpeed,
			"tx_speed": txSpeed,
		},
		"uptime":        uptime,
		"temperature":   temperature,
		"top_processes": topProcesses,
	}
	return result, nil
}

func readTemperature() float64 {
	temps, err := host.SensorsTemperatures()
	if err != nil || len(temps) == 0 {
		return 0
	}
	for _, t := range temps {
		if t.Temperature > 0 {
			return t.Temperature
		}
	}
	return 0
}

func (a *Agent) calculateNetSpeed(rx, tx uint64) (float64, float64) {
	a.netMu.Lock()
	defer a.netMu.Unlock()

	now := time.Now()
	if a.lastNetAt.IsZero() {
		a.lastNetAt = now
		a.lastRX = rx
		a.lastTX = tx
		return 0, 0
	}

	seconds := now.Sub(a.lastNetAt).Seconds()
	if seconds <= 0 {
		return 0, 0
	}
	if rx < a.lastRX || tx < a.lastTX {
		a.lastNetAt = now
		a.lastRX = rx
		a.lastTX = tx
		return 0, 0
	}

	rxSpeed := float64(rx-a.lastRX) / seconds
	txSpeed := float64(tx-a.lastTX) / seconds

	a.lastNetAt = now
	a.lastRX = rx
	a.lastTX = tx

	return rxSpeed, txSpeed
}

func (a *Agent) calculateDiskSpeed(readBytes, writeBytes uint64) (float64, float64) {
	a.diskMu.Lock()
	defer a.diskMu.Unlock()

	now := time.Now()
	if a.lastDiskAt.IsZero() {
		a.lastDiskAt = now
		a.lastDiskRead = readBytes
		a.lastDiskWrite = writeBytes
		return 0, 0
	}

	seconds := now.Sub(a.lastDiskAt).Seconds()
	if seconds <= 0 {
		return 0, 0
	}
	if readBytes < a.lastDiskRead || writeBytes < a.lastDiskWrite {
		a.lastDiskAt = now
		a.lastDiskRead = readBytes
		a.lastDiskWrite = writeBytes
		return 0, 0
	}

	readSpeed := float64(readBytes-a.lastDiskRead) / seconds
	writeSpeed := float64(writeBytes-a.lastDiskWrite) / seconds

	a.lastDiskAt = now
	a.lastDiskRead = readBytes
	a.lastDiskWrite = writeBytes

	return readSpeed, writeSpeed
}

func (a *Agent) collectProcesses(limit int) ([]map[string]any, error) {
	procs, err := process.Processes()
	if err != nil {
		return nil, err
	}

	type procInfo struct {
		PID  int32
		Name string
		CPU  float64
		Mem  float32
	}

	items := make([]procInfo, 0, len(procs))
	for _, p := range procs {
		name, err := p.Name()
		if err != nil || name == "" {
			continue
		}
		cpuPercent, _ := p.CPUPercent()
		memPercent, _ := p.MemoryPercent()
		items = append(items, procInfo{
			PID:  p.Pid,
			Name: name,
			CPU:  cpuPercent,
			Mem:  memPercent,
		})
	}

	sort.Slice(items, func(i, j int) bool {
		return items[i].CPU > items[j].CPU
	})

	if limit > 0 && len(items) > limit {
		items = items[:limit]
	}

	result := make([]map[string]any, 0, len(items))
	for _, item := range items {
		result = append(result, map[string]any{
			"pid":  item.PID,
			"name": item.Name,
			"cpu":  item.CPU,
			"mem":  item.Mem,
		})
	}

	return result, nil
}

func killProcess(pid int) error {
	proc, err := os.FindProcess(pid)
	if err != nil {
		return err
	}
	return proc.Kill()
}

func (a *Agent) openTerminal(sessionID string, rows, cols int) error {
	if rows <= 0 {
		rows = 24
	}
	if cols <= 0 {
		cols = 80
	}

	shell := strings.TrimSpace(os.Getenv("SHELL"))
	if shell == "" {
		shell = "bash"
	}

	cmd := exec.Command(shell)
	ptmx, err := pty.StartWithSize(cmd, &pty.Winsize{
		Rows: uint16(rows),
		Cols: uint16(cols),
	})
	if err != nil {
		return err
	}

	a.termMu.Lock()
	if existing := a.terminals[sessionID]; existing != nil {
		_ = existing.ptyFile.Close()
		if existing.cmd.Process != nil {
			_ = existing.cmd.Process.Kill()
		}
	}
	a.terminals[sessionID] = &terminalSession{cmd: cmd, ptyFile: ptmx}
	a.termMu.Unlock()

	go a.streamTerminalOutput(sessionID, ptmx)
	return nil
}

func (a *Agent) streamTerminalOutput(sessionID string, ptmx *os.File) {
	buf := make([]byte, 4096)
	for {
		n, err := ptmx.Read(buf)
		if n > 0 {
			_ = a.sendJSON(map[string]any{
				"type":       "terminal_output",
				"session_id": sessionID,
				"data":       string(buf[:n]),
			})
		}
		if err != nil {
			a.closeTerminal(sessionID)
			return
		}
	}
}

func (a *Agent) writeTerminalInput(sessionID, data string) error {
	a.termMu.RLock()
	session := a.terminals[sessionID]
	a.termMu.RUnlock()
	if session == nil {
		return errors.New("terminal session not found")
	}
	_, err := session.ptyFile.Write([]byte(data))
	return err
}

func (a *Agent) resizeTerminal(sessionID string, rows, cols int) error {
	if rows <= 0 || cols <= 0 {
		return errors.New("invalid resize dimensions")
	}
	if rows > 1000 || cols > 1000 {
		return errors.New("resize dimensions are too large")
	}

	a.termMu.RLock()
	session := a.terminals[sessionID]
	a.termMu.RUnlock()
	if session == nil {
		return errors.New("terminal session not found")
	}

	return pty.Setsize(session.ptyFile, &pty.Winsize{Rows: uint16(rows), Cols: uint16(cols)})
}

func (a *Agent) closeTerminal(sessionID string) {
	a.termMu.Lock()
	session := a.terminals[sessionID]
	delete(a.terminals, sessionID)
	a.termMu.Unlock()
	if session == nil {
		return
	}

	_ = session.ptyFile.Close()
	if session.cmd.Process != nil {
		_ = session.cmd.Process.Kill()
	}
}

func (a *Agent) closeAllTerminals() {
	a.termMu.Lock()
	all := a.terminals
	a.terminals = make(map[string]*terminalSession)
	a.termMu.Unlock()

	for _, session := range all {
		_ = session.ptyFile.Close()
		if session.cmd.Process != nil {
			_ = session.cmd.Process.Kill()
		}
	}
}

func (a *Agent) runDeploy(payload deployPayload) {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Minute)
	defer cancel()

	logf := func(line string, isErr bool) {
		if strings.TrimSpace(line) == "" {
			return
		}
		a.sendDeployLog(payload.DeployID, line, isErr)
	}
	finish := func(success bool, deployURL, errText string) {
		_ = a.sendJSON(map[string]any{
			"type":      "deploy_complete",
			"deploy_id": payload.DeployID,
			"success":   success,
			"url":       deployURL,
			"error":     errText,
		})
	}

	workDir, err := os.MkdirTemp("", fmt.Sprintf("novex-deploy-%d-*", payload.DeployID))
	if err != nil {
		finish(false, "", err.Error())
		return
	}
	defer os.RemoveAll(workDir)

	sourceDir := filepath.Join(workDir, "src")
	switch strings.ToLower(strings.TrimSpace(payload.Source)) {
	case "github":
		if strings.TrimSpace(payload.RepoURL) == "" {
			finish(false, "", "repo_url is required")
			return
		}
		branch := strings.TrimSpace(payload.Branch)
		if branch == "" {
			branch = "main"
		}
		if err := a.runLoggedCommand(ctx, payload.DeployID, workDir, nil, "git", "clone", "--branch", branch, payload.RepoURL, "src"); err != nil {
			finish(false, "", err.Error())
			return
		}
	case "zip":
		if strings.TrimSpace(payload.ZipData) == "" {
			finish(false, "", "zip_data is required")
			return
		}
		if err := os.MkdirAll(sourceDir, 0o755); err != nil {
			finish(false, "", err.Error())
			return
		}
		if err := unzipBase64(payload.ZipData, sourceDir); err != nil {
			finish(false, "", err.Error())
			return
		}
	default:
		finish(false, "", "unsupported source")
		return
	}

	sourceDir = normalizeSourceRoot(sourceDir)
	projectType := detectProjectType(sourceDir, payload.ProjectType)
	port, err := findFreePort()
	if err != nil {
		finish(false, "", err.Error())
		return
	}

	logf("Detected project type: "+projectType, false)

	switch projectType {
	case "docker":
		tag := fmt.Sprintf("deploy-%d", payload.DeployID)
		if err := a.runLoggedCommand(ctx, payload.DeployID, sourceDir, nil, "docker", "build", "-t", tag, "."); err != nil {
			finish(false, "", err.Error())
			return
		}
		containerName := fmt.Sprintf("deploy-%d-%d", payload.DeployID, time.Now().Unix())
		if err := a.runLoggedCommand(ctx, payload.DeployID, sourceDir, nil, "docker", "run", "-d", "--name", containerName, "-p", fmt.Sprintf("%d:80", port), tag); err != nil {
			finish(false, "", err.Error())
			return
		}
	case "go":
		if err := a.runLoggedCommand(ctx, payload.DeployID, sourceDir, nil, "go", "build", "-o", "app", "."); err != nil {
			finish(false, "", err.Error())
			return
		}
		pid, err := startDetached(sourceDir, []string{fmt.Sprintf("PORT=%d", port)}, "./app")
		if err != nil {
			finish(false, "", err.Error())
			return
		}
		logf(fmt.Sprintf("Started Go process pid=%d", pid), false)
	case "react":
		if err := a.runLoggedCommand(ctx, payload.DeployID, sourceDir, nil, "npm", "install"); err != nil {
			finish(false, "", err.Error())
			return
		}
		if err := a.runLoggedCommand(ctx, payload.DeployID, sourceDir, nil, "npm", "run", "build"); err != nil {
			finish(false, "", err.Error())
			return
		}
		pid, err := startDetached(sourceDir, nil, "npx", "--yes", "serve", "-s", "build", "-l", fmt.Sprintf("%d", port))
		if err != nil {
			finish(false, "", err.Error())
			return
		}
		logf(fmt.Sprintf("Started static server pid=%d", pid), false)
	case "node":
		if err := a.runLoggedCommand(ctx, payload.DeployID, sourceDir, nil, "npm", "install"); err != nil {
			finish(false, "", err.Error())
			return
		}

		hasBuild, _ := hasBuildScript(sourceDir)
		if hasBuild {
			if err := a.runLoggedCommand(ctx, payload.DeployID, sourceDir, nil, "npm", "run", "build"); err != nil {
				finish(false, "", err.Error())
				return
			}
		}

		if dirExists(filepath.Join(sourceDir, "build")) {
			pid, err := startDetached(sourceDir, nil, "npx", "--yes", "serve", "-s", "build", "-l", fmt.Sprintf("%d", port))
			if err != nil {
				finish(false, "", err.Error())
				return
			}
			logf(fmt.Sprintf("Started build server pid=%d", pid), false)
		} else {
			pid, err := startDetached(sourceDir, []string{fmt.Sprintf("PORT=%d", port)}, "npm", "start")
			if err != nil {
				finish(false, "", err.Error())
				return
			}
			logf(fmt.Sprintf("Started node process pid=%d", pid), false)
		}
	default:
		finish(false, "", "unsupported project type")
		return
	}

	url := fmt.Sprintf("http://%s:%d", detectLocalIP(), port)
	finish(true, url, "")
}

func (a *Agent) sendDeployLog(deployID uint, line string, isErr bool) {
	_ = a.sendJSON(map[string]any{
		"type":      "deploy_log",
		"deploy_id": deployID,
		"line":      line,
		"is_error":  isErr,
	})
}

func (a *Agent) runLoggedCommand(ctx context.Context, deployID uint, dir string, env []string, name string, args ...string) error {
	_ = a.sendJSON(map[string]any{
		"type":      "deploy_log",
		"deploy_id": deployID,
		"line":      "$ " + name + " " + strings.Join(args, " "),
		"is_error":  false,
	})

	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), env...)

	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return err
	}
	stderr, err := cmd.StderrPipe()
	if err != nil {
		return err
	}

	if err := cmd.Start(); err != nil {
		return err
	}

	var wg sync.WaitGroup
	pump := func(reader io.Reader, isErr bool) {
		defer wg.Done()
		scanner := bufio.NewScanner(reader)
		buf := make([]byte, 0, 64*1024)
		scanner.Buffer(buf, 1024*1024)
		for scanner.Scan() {
			line := scanner.Text()
			a.sendDeployLog(deployID, line, isErr)
		}
	}

	wg.Add(2)
	go pump(stdout, false)
	go pump(stderr, true)

	waitErr := cmd.Wait()
	wg.Wait()
	if waitErr != nil {
		return waitErr
	}
	return nil
}

func detectProjectType(sourceDir, requested string) string {
	requested = strings.ToLower(strings.TrimSpace(requested))
	if requested != "" && requested != "auto" {
		return requested
	}

	if fileExists(filepath.Join(sourceDir, "Dockerfile")) {
		return "docker"
	}
	if fileExists(filepath.Join(sourceDir, "go.mod")) {
		return "go"
	}
	if fileExists(filepath.Join(sourceDir, "package.json")) {
		if hasReactProject(sourceDir) {
			return "react"
		}
		return "node"
	}
	return "react"
}

func hasReactProject(sourceDir string) bool {
	packageJSON := filepath.Join(sourceDir, "package.json")
	content, err := os.ReadFile(packageJSON)
	if err != nil {
		return false
	}
	var parsed struct {
		Dependencies    map[string]any `json:"dependencies"`
		DevDependencies map[string]any `json:"devDependencies"`
	}
	if err := json.Unmarshal(content, &parsed); err != nil {
		return false
	}
	if _, ok := parsed.Dependencies["react"]; ok {
		return true
	}
	if _, ok := parsed.DevDependencies["react"]; ok {
		return true
	}
	return false
}

func hasBuildScript(sourceDir string) (bool, error) {
	content, err := os.ReadFile(filepath.Join(sourceDir, "package.json"))
	if err != nil {
		return false, err
	}
	var parsed struct {
		Scripts map[string]any `json:"scripts"`
	}
	if err := json.Unmarshal(content, &parsed); err != nil {
		return false, err
	}
	_, ok := parsed.Scripts["build"]
	return ok, nil
}

func startDetached(dir string, env []string, name string, args ...string) (int, error) {
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), env...)

	devNull, err := os.OpenFile(os.DevNull, os.O_RDWR, 0)
	if err == nil {
		defer devNull.Close()
		cmd.Stdin = devNull
		cmd.Stdout = devNull
		cmd.Stderr = devNull
	}

	if err := cmd.Start(); err != nil {
		return 0, err
	}
	pid := cmd.Process.Pid
	go cmd.Wait()
	return pid, nil
}

func unzipBase64(zipData, targetDir string) error {
	decoded, err := base64.StdEncoding.DecodeString(zipData)
	if err != nil {
		decoded, err = base64.RawStdEncoding.DecodeString(zipData)
		if err != nil {
			return err
		}
	}

	zr, err := zip.NewReader(bytes.NewReader(decoded), int64(len(decoded)))
	if err != nil {
		return err
	}

	basePath := filepath.Clean(targetDir) + string(os.PathSeparator)
	for _, f := range zr.File {
		path := filepath.Join(targetDir, f.Name)
		cleanPath := filepath.Clean(path)
		if !strings.HasPrefix(cleanPath+string(os.PathSeparator), basePath) && cleanPath != filepath.Clean(targetDir) {
			return fmt.Errorf("invalid zip path: %s", f.Name)
		}

		if f.FileInfo().IsDir() {
			if err := os.MkdirAll(cleanPath, 0o755); err != nil {
				return err
			}
			continue
		}

		if err := os.MkdirAll(filepath.Dir(cleanPath), 0o755); err != nil {
			return err
		}

		rc, err := f.Open()
		if err != nil {
			return err
		}
		out, err := os.OpenFile(cleanPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, f.Mode())
		if err != nil {
			rc.Close()
			return err
		}
		_, copyErr := io.Copy(out, rc)
		closeErr := out.Close()
		rcCloseErr := rc.Close()
		if copyErr != nil {
			return copyErr
		}
		if closeErr != nil {
			return closeErr
		}
		if rcCloseErr != nil {
			return rcCloseErr
		}
	}
	return nil
}

func normalizeSourceRoot(sourceDir string) string {
	entries, err := os.ReadDir(sourceDir)
	if err != nil || len(entries) != 1 || !entries[0].IsDir() {
		return sourceDir
	}
	return filepath.Join(sourceDir, entries[0].Name())
}

func findFreePort() (int, error) {
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return 0, err
	}
	defer listener.Close()
	return listener.Addr().(*net.TCPAddr).Port, nil
}

func detectLocalIP() string {
	ifaces, err := net.Interfaces()
	if err != nil {
		return "127.0.0.1"
	}
	for _, iface := range ifaces {
		if iface.Flags&net.FlagUp == 0 || iface.Flags&net.FlagLoopback != 0 {
			continue
		}
		addrs, err := iface.Addrs()
		if err != nil {
			continue
		}
		for _, addr := range addrs {
			var ip net.IP
			switch v := addr.(type) {
			case *net.IPNet:
				ip = v.IP
			case *net.IPAddr:
				ip = v.IP
			}
			if ip == nil || ip.IsLoopback() {
				continue
			}
			ipv4 := ip.To4()
			if ipv4 != nil {
				return ipv4.String()
			}
		}
	}
	return "127.0.0.1"
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func dirExists(path string) bool {
	info, err := os.Stat(path)
	if err != nil {
		return false
	}
	return info.IsDir()
}
